### PR TITLE
Corrected some mistakes in the english version and started the french translation

### PR DESCRIPTION
**Pull request by Krypta1**
Hi, first of all, thenk you. What you have done is amazing.

I started the french translation of your mod but I don't know if I'm doing it right, please give me a little feedback

I've also corrected some mistakes I've seen in the english version

Cheers !

### CODE REVIEW

**Comment by Taludas** [comment]
Thank you very, very much! Very good work and I'll certainly try to implement it for the next update! Also, good catch on the typos, even though the "Stowage Platform" is directly taken from the vanilla modules and the neta testers even criticised me for changing that to "storage" for that building, so I had to do it lole that xD

**Comment by Taludas** [comment]
Did you extract the original French text xml front be RDA and add your translations to that? Because if you only took the English file I provided in the mod, then it changes everything to English ofc.

**Comment by Krypta1** [comment]
Yep, I used your file

Which .rda should I use? I've explored some of the game files but for what I've seen the texts_french.xml appears in more multiple files

**Comment by Taludas** [comment]
Always use the file from the latest rda you find. Those files are overwritten from the one with the smallest number to the one with the highest number.

**Comment by Taludas** [comment]
Have included your contribution in the current release

**Pull request closed without merging**
